# <PROJECT_NAME> Justfile

# 编译
build:
    go build -o bin/$(basename $(pwd)) .

# 测试
test:
    go test ./... -race

test-cov:
    go test ./... -coverprofile=coverage.out
    go tool cover -html=coverage.out -o coverage.html

# Lint
lint:
    golangci-lint run

fmt:
    gofumpt -l .

fmt-check:
    gofumpt -d .

# 安装
tools:
    go install github.com/mgechev/revive@latest
    go install mvdan.cc/gofumpt@latest

hooks:
    pre-commit install

# 默认
_default:
    @just --list
